### ISSUE TITLE
[Feature Request] - Make Cup be able to trigger integrations

### ISSUE THREAD

**Issue by steveiliop56** [sergi0g/cup#37] opened 2024-10-12 10:06 UTC
Hello again (again),

> Cup cannot directly trigger your integrations. If you want that to happen automatically, please use What's up Docker instead. Cup was created to be simple.

I don't really agree with this. I understand how Cup is designed and want to keep this nice and simple UI, but by not allowing triggering integrations it is harder for people to integrate to their workflows. My ideal solutions is to keep Cup simple ***looking*** but make it extremely powerful on the backend. By this I mean, keeping the clean and fast UI while allowing a ton of customization on the backend. For the trigger to work you would need a thread to check for updates regularly just like I mentioned in #35. Hope this gets implemented because it will make Cup a game changer!

**Comment by sergi0g** [comment] 2024-10-12 12:56
Hello @steveiliop56! This issue looks like a duplicate of #35 and my answer there applies here, so I will close it. If you feel that it isn't a duplicate, please reopen it.

**Closed by sergi0g** 2024-10-12 12:56 UTC
Labels: duplicate
