### ISSUE TITLE
[BUG] Theme not work

### ISSUE THREAD

**Issue by Vctrsnts** [sergi0g/cup#45] opened 2024-10-28 19:45 UTC
**Describe the bug**
Hi.
Using _docker compose_ with my `cup.json` with this code:
```
{
     "theme": "blue"
}
```
And the theme of cup is white. I read the documentation about this and put the same. I dont have any error in the logs.

The `docker-compose.yml` is this:

 ```
cup:
   image: ghcr.io/sergi0g/cup:latest
   container_name: cup # Optional
   restart: unless-stopped
   networks:
     - internal
   command: -c /config/cup.json serve
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ${HOME}/config/cup/cup.json:/config/cup.json
   labels:
     - traefik.enable=true
     - traefik.http.services.cup.loadbalancer.server.port=8000
     - traefik.http.routers.cup.entrypoints=websecure
     - traefik.http.routers.cup-secure.middlewares=myauth@file
     - traefik.http.routers.cup.rule=Host(`${CUP_SERVER}`)
```

**System info (please complete the following information):**
 - OS: Debian Stable
 - Docker daemon version: 27.3.1
 - Cup version: latest

**Additional context**
In the server using _traefik_, and access to cup with `cups.mydomaing.duckdns.org`. The labels _traefik_ on `docker-compose.yml` is for this.

**Comment by sergi0g** [comment] 2024-10-29 13:47
Hello @Vctrsnts!

This is not a bug! The way theming works is that it sets a base color and then what you see depends on your system theme. On a system with dark mode enabled, the blue and the default theme look very different: one is dark blue, while the other is gray. On a system with light mode (yours) the difference between the two themes is almost unnoticeable as the color saturation is very low. 

If you want the blue theme you asked for, all you need to do is turn on dark mode for your browser or system.

If you think that theming based on the system color should be optional (i.e. you should be able to choose dark blue for every device, even if the system is in light mode), please open another issue asking for that.

I'm closing this issue now.

**Closed** 2024-10-29 13:47 UTC
Labels: bug
