### ISSUE TITLE
Failed to authenticate to registry

### ISSUE THREAD

**Issue by lukasMega** [sergi0g/cup#18] opened 2024-07-22 07:40 UTC
```
...nPEi_nESiKrpUa8Gof1s-Hzzz22MEfGA3acSXO9177U7m-uPVZWHrceBEzesjAiedYvu3e26LJ7rCanNPVegVjI886qgmAaP_FGnxi_lz2sUObjPFXQhN78dZbM8cLNg8dgn1__G2j3LJngm5kebmjXdCh_jQrHFMhG45bjpui-GA

Failed to authenticate to registry nabo.codimd.dev with given token!
```

when i added https://github.com/hackmdio/codimd/blob/develop/deployments/docker-compose.yml
I'm getting this error and Cup is unavailable

**Comment by sergi0g** [comment] 2024-07-22 08:21
Hello @lukasMega! Sorry for this issue. To help debug, can you please run Cup again and provide the full token from the output?

**Comment by sergi0g** [comment] 2024-07-22 08:51
Hi again! I can reproduce your issue. I'm not sure what goes wrong here, so I'll have to manually try to reproduce. However, `nabo.codimd.dev` just redirects to docker hub, so as a temporary workaround just change the image you're pulling to `hackmdio/hackmd:2.5.3`. Finally, please remember to delete the old image with `docker rmi nabo.codimd.dev/hackmdio/hackmd:2.5.3` so Cup doesn't give you any more errors.

**Comment by lukasMega** [comment] 2024-07-25 22:42
Thank you. It will be closed or do you consider to handle such case? It would be great.

**Comment by sergi0g** [comment] 2024-07-26 11:24
I will not close this issue. I need to find the problem because this might affect other registries too.

**Comment by sergi0g** [comment] 2024-09-15 17:40
It seems `docker.getoutline.com` has the same issue.

**Comment by ritzdan** [comment] 2024-10-04 11:28
Same issue with self-hosted gitea with the following stdout:
```
⠋ Checking...                                                                   
[2K⠙ Checking...                                                                   
[2K⠹ Checking...                                                                   
[2K⠸ Checking...                                                                   
[2K⠼ Checking...                                                                   
[2K⠴ Checking...                                                                   
[2K⠦ Checking...                                                                   
[2K⠧ Checking...                                                                   
[2K⠇ Checking...                                                                   
[2K⠋ Checking...                                                                   
[2K⠙ Checking...                                                                   
[2K⠹ Checking...                                                                   
[2K⠸ Checking...                                                                   
[103m WARN  
[0m Failed to authenticate to registry git.tools.cloudfor.ge with given token!
{token string removed, not sure if it is sensitive}
[2K⠼ Checking...                                                                   
[2K⠴ Checking...                                                                   
[2K⠦ Checking...                                                                   
[2K⠧ Checking...                                                                   
[2K⠇ Checking...                                                                   
[2K⠋ Checking...                                                                   
[2K⠙ Checking...                                                                   
[2K⠹ Checking...                                                                   
[2K⠸ Checking...                                                                   
[2K⠼ Checking...                                                                   
[2K⠴ Checking...                                                                   
[2K⠦ Checking...                                                                   
[2K⠧ Checking...                                                                   
[2K⠇ Checking...                                                                   
[2K⠋ Checking...                                                                   
[2K⠙ Checking...                                                                   
[2K⠹ Checking...                                                                   
[2K⠸ Checking...                                                                   
[2K⠼ Checking...                                                                   
[2K⠴ Checking...                                                                   
[2K⠦ Checking...                                                                   
[2K⠧ Checking...                                                                   
[2K⠇ Checking...                                                                   
[2K⠋ Checking...                                                                   
[2K⠙ Checking...                                                                   
[2K⠹ Checking...                                                                   
[2K⠸ Checking...                                                                   
[2K⠼ Checking...                                                                   
[2K
[32;1m✓
[0m Done!
thread 'main' panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sergi0g** [comment] 2024-10-04 12:05
@ritzdan have you configured authentication for your self hosted registry in the `config.json`?

**Comment by ritzdan** [comment] 2024-10-04 14:29
Sorry, should have included the following.   I am using the same access token as I use for docker login to pull the image.

/tmp/config.json:
```
{
    "authentication": {
        "gitea.xxxxx.xxx": "xxxxxxxxxxx"
    }
}
```

command:
```
docker run \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/cup.json:/config/cup.json \
    -t ghcr.io/sergi0g/cup check -i
```

**Comment by sergi0g** [comment] 2024-10-10 17:21
@ritzdan sorry for not replying! I will test with my local Gitea instance ASAP and I'll get back to you. Last time I tested it worked fine, so I'm thinking this whole issue might be related to the reverse proxy used. I still need to gather more info though.

**Comment by sergi0g** [comment] 2024-10-11 12:56
Hey again @ritzdan! I tested with my local Gitea instance and it worked fine, so I thought the problem was probably on your end.

It turns out that you forgot to pass the configuration to the command. Here it is corrected:
```
docker run \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/config.json:/config/cup.json \
    -t ghcr.io/sergi0g/cup -c /config/cup.json check -i
```
It's mentioned in the docs [here](https://sergi0g.github.io/cup/docs/configuration#run-cup-with-the-new-configuration-file).

**Comment by johnnyggalt** [comment] 2024-10-16 03:29
After updating to latest build (not sure if that triggered the issue), I am getting this:

```
WARN  Failed to authenticate to registry registry-1.docker.io with given token!
```

Is there a way to remove the cached token? Might be nice to include that in the message.

**Comment by sergi0g** [comment] 2024-10-25 16:41
I debugged this properly and it seems that the only thing Docker CLI is doing different is using the URL the registry redirects to as the registry and makes all subsequent requests there. Fixing the problem would require significant code changes that would change the way Cup works. Since this problem affects very few users, I will close this issue.

**Closed by sergi0g** 2024-10-25 16:41 UTC
Labels: bug

**Comment by parasiteoflife** [comment] 2025-11-25 05:12
I'm having a similar issue with my forgejo instanace, I provided the token even in the new config format, I was using an old one where everything was under the authentication dict, and I'm still getting

```
cup  |  INFO Starting server, please wait...
cup  |  WARN GET https://forgejo.xxxxxx.xxx/v2/token?&service=container_registry&scope=*&scope=repository:parasiteoflife/test_docker_backend:pull&scope=repository:parasiteoflife/test_docker:pull: Unauthorized! Please configure authentication for this registry or if you have already done so, please make sure it is correct.
cup  | ERROR GET https://forgejo.xxxxxx.xxx/v2/token?&service=container_registry&scope=*&scope=repository:parasiteoflife/test_docker_backend:pull&scope=repository:parasiteoflife/test_docker:pull: Request failed!
```

cup.json
```json
{
    "registries": {
        "forgejo.xxxxxxx.xxx": {
            "authentication": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        }
    }
}
``` 

the same token works with Komodo

**Comment by parasiteoflife** [comment] 2025-11-25 05:22
Ok I just found out it's a permission issue, cup expects the token to have more permissions than what it needs, I gave it read permission for repo and packages (though I guess only packages should be required?) and it didn't work, if I give every write permission it works, so this is indeed a bug @sergi0g

**Comment by sergi0g** [comment] 2025-11-25 14:14
Hey @parasiteoflife,
Can you try using `docker login` with the basic token (just package read scope) and pulling an image from your private registry with it?

**Comment by parasiteoflife** [comment] 2025-11-25 15:11
Sorry, I was wrong, even with all permissions it doesn't work, I was just setting socket to none which made it check no image.

I tried login and pull with the package read-only token and it worked

**Comment by sergi0g** [comment] 2025-11-26 05:23
Please make sure that the token you're using for Cup is the same one in your `~/.docker/config.json`.

**Comment by parasiteoflife** [comment] 2025-11-27 16:36
Yes, I tried this on another machine to avoid this
